name: warranty_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  dio: ^5.3.3
  get: 4.6.6
  talker_flutter: ^3.5.4
  data_table_2: ^2.5.8
  image_picker: ^1.0.4
  fl_chart: ^0.64.0
  connectivity_plus: ^5.0.0
  qr_flutter: ^4.1.0
  printing: ^5.11.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_web_plugins:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - web/assets/
